env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2020
rules:
  no-underscore-dangle:
    - error
    - allow:
        - _id
  no-param-reassign:
    - error
    - props: false
  "@typescript-eslint/explicit-module-boundary-types":
    - off
