service: ib-cyberpunk-barbershop
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true
functions:
  graphql:
    handler: src/handlers.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
custom:
  contentCompression: 1024
  webpack:
    includeModules: true
    forceExclude:
      - aws-sdk
    packager: yarn
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-api-compression
